### ISSUE TITLE
Request for Access to scRNA-seq Data for MSC Signature Validation

### ISSUE THREAD

**Issue by TPOW-001** [shovikb94/spatial-bonemarrow-atlas#1]
Hello,

Firstly, I would like to extend my gratitude for your team's remarkable efforts in providing the invaluable human bone marrow-associated scRNA-seq data on GEO. The data has been instrumental in our research, as we are currently focused on "Discovering the MSC signatures" by leveraging the transcriptome data from MSC associated databases.

Recently, while analyzing the MSC signatures within a human bone marrow scRNA-seq database (GSE190965, Li et al, Elife 2023), we observed a compelling expression pattern within the stromal clusters. This finding has piqued our interest in further validating our MSC signatures. 
![1](https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/68772262/d59a6b89-244c-4945-b639-23e22ebcf6f4)
![2](https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/68772262/d60e3456-85be-4d7e-8fe5-73853e035582)

In light of this, we are eager to extend our analysis to include your scRNA-seq data. Would it be possible for you to share the related .rds files that were analyzed with Seurat, as depicted in Fig1B and 2A of your esteemed publication? Access to the .rds file, containing UMAP coordinates, meta-information, and scRNA-seq data, would be immensely beneficial to our study.
(We have downloaded the data file 'Normal_Bone_Marrow_CODEX_Atlas_Seurat_v2.rds' from GSE253355, but unfortunately, the metadata info of this dataset does not include categories such as Osteo-MSC, APOD+ MSC, Fibro-MSC, etc.)

![image](https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/68772262/ba45b583-eabc-49a3-b8aa-c94d35cab905)
![image](https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/68772262/6ddf9de1-75f7-4efe-b549-2f2f14f4c8e2)

We would be deeply appreciative of any assistance you could provide in facilitating access to the required data. 
Your support would significantly advance our understanding in this domain. 

Thank you once again for your remarkable contributions to the field. We are looking forward to your favorable response. 

Sincerely,

Chia-Chi Chang

**Comment by shovikb94** [comment]
Thanks for your kind words and interest in our data. The cluster annotations are indeed in the provided GEO Seurat object under "cluster_anno_l2", I just downloaded the object and double-checked. However, we are also in the process of uploading an MSC only RDS file to GEO which has the UMAP coordinates in Figure 2A and is already filtered down to the highest-quality/confidence MSCs as we recognize it may be easier for users to use for mapping tasks - please stay tuned for that. I will post a comment here and close this issue once that has posted, just give us a few days. 

Thanks again and hope this is helpful!

**Comment by TPOW-001** [comment]
First of all, thank you for responding so quickly to our queries and for providing us with the relevant data.

However, based on the code below, we still encounter some issues. 

The first issue is that the UMAP coordinates provided in 'Normal_Bone_Marrow_CODEX_Atlas_Seurat_v2.rds' are for Fig. 4C, but it lacks the UMAP coordinates for Fig. 1B. 

The second issue is that the 'cluster_anno_l2' categorization does not fully correspond to the cell types shown in Fig 1B, such as RNAlo MSC, Adipo MSC, Osteo-MSC, etc. 

Therefore, we would like to kindly request you to provide the RDS file for Fig. 1B. Once again, thank you for your prompt reply and assistance.

`rm(list=ls(all=T))
library(dplyr)
library(Seurat)
library(ggplot2)
library(patchwork)
library(clusterProfiler)
library(cellchat)
setwd("/workspace/240513 GSE253355/0. Original data/Processed CODEX Data")
da0<-readRDS("Normal_Bone_Marrow_CODEX_Atlas_Seurat_v2.rds", refhook = NULL)

DefaultAssay(da0) <- "integrated"
Idents(da0) <- factor(da0$cluster_anno_l1, 
                      levels = sort(rownames(table(da0$cluster_anno_l1))))
p1 <- DimPlot(da0, reduction = 'UMAP_dim30', label.size = 4, label = F) + theme(legend.position = "right")
p1
x1<- da0@meta.data[["cluster_anno_l1"]] %>%
         table() %>%
         as.matrix()

Idents(da0) <- factor(da0$cluster_anno_l2, 
                      levels = sort(rownames(table(da0$cluster_anno_l2))))
p2 <- DimPlot(da0, reduction = 'UMAP_dim30', label.size = 4, label = F) + theme(legend.position = "right")
p2
x2<- da0@meta.data[["cluster_anno_l2"]] %>%
         table() %>%
         as.matrix()

Idents(da0) <- factor(da0$cluster_anno_coarse, 
                      levels = sort(rownames(table(da0$cluster_anno_coarse))))
p3 <- DimPlot(da0, reduction = 'UMAP_dim30', label.size = 4, label = F) + theme(legend.position = "right")
p3
x3<- da0@meta.data[["cluster_anno_coarse"]] %>%
         table() %>%
          as.matrix()
p1+p2+p3
`
![image](https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/68772262/a91c1d1b-4455-468c-b737-5a1a107fd83f)

**Comment by shovikb94** [comment]
Hi - apologies, I thought you had said you had downloaded the object from GEO. Per our manuscript, the scRNA-Seq processed data is provided through [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE253355). The file you have downloaded is the CODEX processed object from FigShare, which you can tell because it says "CODEX" in the name. We could not upload our CODEX data to GEO as it is not sequencing or expression data. The scRNA-Seq processed object from which you can recreate Figure 1B is available through GEO. The MSC scRNA-Seq object is being uploaded to the same GEO repository as I mentioned, but you can create basically the same plot using the annotations in the current full atlas object. Hope this helps and sorry for any confusion. 
<img width="987" alt="DataAvailabilityTable" src="https://github.com/shovikb94/spatial-bonemarrow-atlas/assets/77076353/922fb3a7-3b26-4c67-83a0-116750d69fd6">

**Comment by TPOW-001** [comment]
Thank you for clarifying my misunderstanding.  

I was under the impression that both the CODEX and scRNA-seq data had been integrated, which led me to mistakenly assume that 'Normal_Bone_Marrow_CODEX_Atlas_Seurat_v2.rds' and 'GSE253355_Normal_Bone_Marrow_Atlas_Seurat_SB_v2' were the same file. I have now correctly accessed all the information for Fig. 1B. 

Once again, I appreciate your assistance, and I eagerly await the data related to Fig. 2A. Wishing you all the best.

**Comment by shovikb94** [comment]
Happy to help! The MSC object is now uploaded to the same GEO repository.

**Comment by TPOW-001** [comment]
Thank you for your help and patience in resolving the difficulties I previously encountered. Now, we can attempt to see if the MSC signatures we found can be validated on your scRNA-seq data. I will now close this issue. Thank you again for your assistance.
